changed app destination for docker image pull

diff --git a/.github/workflows/deploy-worker.yml b/.github/workflows/deploy-worker.yml
--- a/.github/workflows/deploy-worker.yml
+++ b/.github/workflows/deploy-worker.yml
@@ -71,8 +71,7 @@ jobs:
             echo $GHCR_PAT | docker login ghcr.io -u $USERNAME --password-stdin
 
             # 2. Navigate to project root (Infrastructure as Code location)
-            # You must change this path to match your server location
-            cd ~/home_os/apps/worker || { echo "❌ Directory not found"; exit 1; }
+            cd /opt/mqtt-worker || { echo "❌ Directory not found"; exit 1; }
 
             # 3. Pull the specific service
             echo "⬇️ Pulling latest worker image..."
